window.FABLE_PRODUCTS = [
  {
    "id": "blue",
    "name": "Blue Signature Saree",
    "price": 35000,
    "color": "Blue",
    "category": "sarees",
    "label": "Signature Edit",
    "page_main": 2,
    "page_detail": 3,
    "tone": "#34206f",
    "accent": "#d7ba61",
    "description": "A royal blue drape paired with a golden blouse and ornate floral border work for evening celebrations.",
    "fabric": "Flowing festive drape with embellished blouse and embroidered border.",
    "image": "assets/products/blue-main.webp",
    "gallery": [
      "assets/products/blue-main.webp",
      "assets/products/blue-detail-1.webp",
      "assets/products/blue-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "signature",
    "categoryLabel": "Sarees",
    "badge": "Signature Edit",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "golden-tissue",
    "name": "Golden Tissue Saree",
    "price": 25000,
    "color": "Golden Tissue",
    "category": "sarees",
    "label": "Tissue Sarees",
    "page_main": 4,
    "page_detail": 5,
    "tone": "#c9a36a",
    "accent": "#9d3158",
    "description": "A luminous golden tissue saree with soft rose undertones, floral handwork and a contrast magenta finish.",
    "fabric": "Tissue finish saree with floral embroidery and festive blouse detailing.",
    "image": "assets/products/golden-tissue-main.webp",
    "gallery": [
      "assets/products/golden-tissue-main.webp",
      "assets/products/golden-tissue-detail-1.webp",
      "assets/products/golden-tissue-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "tissue",
    "categoryLabel": "Sarees",
    "badge": "Tissue Sarees",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "orange",
    "name": "Orange Festive Saree",
    "price": 30000,
    "color": "Orange",
    "category": "sarees",
    "label": "Festive Sarees",
    "page_main": 6,
    "page_detail": 7,
    "tone": "#c95225",
    "accent": "#111111",
    "description": "A warm orange drape contrasted with a black heavily worked blouse for bold festive styling.",
    "fabric": "Sheer festive drape with contrast embellished blouse and delicate border.",
    "image": "assets/products/orange-main.webp",
    "gallery": [
      "assets/products/orange-main.webp",
      "assets/products/orange-detail-1.webp",
      "assets/products/orange-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "festive",
    "categoryLabel": "Sarees",
    "badge": "Festive Sarees",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "shreenathji",
    "name": "Shreenathji Art Saree",
    "price": 42000,
    "color": "Shreenathji",
    "category": "sarees",
    "label": "Heritage Art",
    "page_main": 8,
    "page_detail": 9,
    "tone": "#bce3dd",
    "accent": "#b14461",
    "description": "A sea-green saree with temple-inspired art motifs, peacock detailing and a rich pink blouse.",
    "fabric": "Art-inspired embroidered saree with narrative motifs and ornate blouse work.",
    "image": "assets/products/shreenathji-main.webp",
    "gallery": [
      "assets/products/shreenathji-main.webp",
      "assets/products/shreenathji-detail-1.webp",
      "assets/products/shreenathji-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "heritage",
    "categoryLabel": "Sarees",
    "badge": "Heritage Art",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "lavender",
    "name": "Lavender Jewel Saree",
    "price": 35000,
    "color": "Lavender",
    "category": "sarees",
    "label": "Signature Edit",
    "page_main": 10,
    "page_detail": 11,
    "tone": "#c6a6d7",
    "accent": "#a41746",
    "description": "A soft lavender drape styled with jewel embellishments and a deep rose blouse for reception-ready elegance.",
    "fabric": "Soft sheer drape with gemstone-style border work and statement blouse details.",
    "image": "assets/products/lavender-main.webp",
    "gallery": [
      "assets/products/lavender-main.webp",
      "assets/products/lavender-detail-1.webp",
      "assets/products/lavender-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "signature",
    "categoryLabel": "Sarees",
    "badge": "Signature Edit",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "silver-tissue",
    "name": "Silver Tissue Saree",
    "price": 30000,
    "color": "Silver Tissue",
    "category": "sarees",
    "label": "Tissue Sarees",
    "page_main": 12,
    "page_detail": 13,
    "tone": "#d8d2c8",
    "accent": "#38206d",
    "description": "A refined silver tissue saree accented with blue blouse embroidery and umbrella-inspired border motifs.",
    "fabric": "Silver tissue drape with blue embroidered blouse and textural finish.",
    "image": "assets/products/silver-tissue-main.webp",
    "gallery": [
      "assets/products/silver-tissue-main.webp",
      "assets/products/silver-tissue-detail-1.webp",
      "assets/products/silver-tissue-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "tissue",
    "categoryLabel": "Sarees",
    "badge": "Tissue Sarees",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "green",
    "name": "Green Floral Saree",
    "price": 30000,
    "color": "Green",
    "category": "sarees",
    "label": "Festive Sarees",
    "page_main": 14,
    "page_detail": 15,
    "tone": "#cdd8bf",
    "accent": "#dd91a7",
    "description": "A pastel green saree with soft floral embroidery and graceful tasseled border accents.",
    "fabric": "Pastel festive drape with floral embroidery, bead details and blouse artistry.",
    "image": "assets/products/green-main.webp",
    "gallery": [
      "assets/products/green-main.webp",
      "assets/products/green-detail-1.webp",
      "assets/products/green-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "festive",
    "categoryLabel": "Sarees",
    "badge": "Festive Sarees",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "black",
    "name": "Black Couture Saree",
    "price": 42000,
    "color": "Black",
    "category": "sarees",
    "label": "Heritage Art",
    "page_main": 16,
    "page_detail": 17,
    "tone": "#0d0d16",
    "accent": "#70ad9d",
    "description": "A dramatic black saree styled with an embroidered couture jacket and metallic handwork.",
    "fabric": "Black statement drape with embellished blouse and ornate embroidered jacket.",
    "image": "assets/products/black-main.webp",
    "gallery": [
      "assets/products/black-main.webp",
      "assets/products/black-detail-1.webp",
      "assets/products/black-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "heritage",
    "categoryLabel": "Sarees",
    "badge": "Heritage Art",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "white-org",
    "name": "White Organza Saree",
    "price": 25000,
    "color": "White Organza",
    "category": "sarees",
    "label": "Organza Sarees",
    "page_main": 18,
    "page_detail": 19,
    "tone": "#f7f4ec",
    "accent": "#181820",
    "description": "A crisp white organza saree with bold black floral linework and a sculpted black blouse.",
    "fabric": "White organza drape with graphic floral embroidery and scalloped accents.",
    "image": "assets/products/white-org-main.webp",
    "gallery": [
      "assets/products/white-org-main.webp",
      "assets/products/white-org-detail-1.webp",
      "assets/products/white-org-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "organza",
    "categoryLabel": "Sarees",
    "badge": "Organza Sarees",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "sea-green",
    "name": "Sea Green Geometric Saree",
    "price": 35000,
    "color": "Sea Green",
    "category": "sarees",
    "label": "Organza Sarees",
    "page_main": 20,
    "page_detail": 21,
    "tone": "#aeb5a5",
    "accent": "#ee544f",
    "description": "A sea-green drape with delicate geometric embroidery, paired with a coral statement blouse.",
    "fabric": "Sheer sea-green drape with geometric handwork and contrast blouse.",
    "image": "assets/products/sea-green-main.webp",
    "gallery": [
      "assets/products/sea-green-main.webp",
      "assets/products/sea-green-detail-1.webp",
      "assets/products/sea-green-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "organza",
    "categoryLabel": "Sarees",
    "badge": "Organza Sarees",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "purple-drape",
    "name": "Purple Drape Set",
    "price": 25000,
    "color": "Purple",
    "category": "drapes",
    "label": "Rakhi Drape",
    "page_main": 2,
    "tone": "#74299a",
    "accent": "#b78b4a",
    "description": "A striking purple drape set with ornate blouse work for a refined festive look.",
    "fabric": "Festive drape set with embroidered blouse and soft flowy lower drape.",
    "image": "assets/products/purple-drape-main.webp",
    "gallery": [
      "assets/products/purple-drape-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "rakhi-drapes",
    "categoryLabel": "Drape Sets",
    "badge": "Rakhi Drape",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "yellow-drape",
    "name": "Yellow Drape Set",
    "price": 17000,
    "color": "Yellow",
    "category": "drapes",
    "label": "Rakhi Drape",
    "page_main": 3,
    "tone": "#d7bf22",
    "accent": "#9b1e33",
    "description": "A sunshine yellow drape silhouette with a structured jacket-inspired top and festive movement.",
    "fabric": "Contemporary draped festive set with jacket detailing and layered lower.",
    "image": "assets/products/yellow-drape-main.webp",
    "gallery": [
      "assets/products/yellow-drape-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "rakhi-drapes",
    "categoryLabel": "Drape Sets",
    "badge": "Rakhi Drape",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "yellow-anarkali",
    "name": "Yellow Anarkali",
    "price": 19000,
    "color": "Yellow",
    "category": "anarkalis",
    "label": "Anarkali",
    "page_main": 4,
    "tone": "#bfa133",
    "accent": "#b53b57",
    "description": "A graceful yellow anarkali finished with rich embroidery and a deep rose dupatta.",
    "fabric": "Flowing anarkali with embroidered neckline and contrast festive dupatta.",
    "image": "assets/products/yellow-anarkali-main.webp",
    "gallery": [
      "assets/products/yellow-anarkali-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "anarkali",
    "categoryLabel": "Anarkalis",
    "badge": "Anarkali",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "peach-sharara",
    "name": "Peach Sharara Set",
    "price": 20000,
    "color": "Peach",
    "category": "festive",
    "label": "Sharara",
    "page_main": 5,
    "tone": "#efc0bd",
    "accent": "#d5a313",
    "description": "A soft peach sharara set styled with a tailored festive jacket and elegant fall.",
    "fabric": "Peach sharara set with jacket-style top, embroidery and wide-leg flow.",
    "image": "assets/products/peach-sharara-main.webp",
    "gallery": [
      "assets/products/peach-sharara-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "sharara",
    "categoryLabel": "Festive Wear",
    "badge": "Sharara",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "red-bandhej",
    "name": "Red Bandhej Set",
    "price": 35000,
    "color": "Red Bandhej",
    "category": "festive",
    "label": "Bandhej",
    "page_main": 6,
    "tone": "#cb1432",
    "accent": "#b78b4a",
    "description": "A rich red bandhej-inspired festive set with statement dupatta and gold accents.",
    "fabric": "Bandhej-style festive kurta set with embellished border and flowing dupatta.",
    "image": "assets/products/red-bandhej-main.webp",
    "gallery": [
      "assets/products/red-bandhej-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "bandhej",
    "categoryLabel": "Festive Wear",
    "badge": "Bandhej",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "beige-anarkali",
    "name": "Beige Anarkali",
    "price": 17000,
    "color": "Beige",
    "category": "anarkalis",
    "label": "Anarkali",
    "page_main": 7,
    "tone": "#ead3a7",
    "accent": "#0d5843",
    "description": "A soft beige anarkali with delicate drawstring details and understated festive elegance.",
    "fabric": "Light beige anarkali with dupatta, handmade tassels and soft border finish.",
    "image": "assets/products/beige-anarkali-main.webp",
    "gallery": [
      "assets/products/beige-anarkali-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "anarkali",
    "categoryLabel": "Anarkalis",
    "badge": "Anarkali",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "blue-jacket-anarkali",
    "name": "Blue Jacket Anarkali",
    "price": 18000,
    "color": "Blue",
    "category": "anarkalis",
    "label": "Jacket Anarkali",
    "page_main": 8,
    "tone": "#30446f",
    "accent": "#9b1e33",
    "description": "A blue anarkali elevated with a short embroidered jacket for a festive yet easy silhouette.",
    "fabric": "Blue anarkali with printed or embroidered jacket and tie-up detailing.",
    "image": "assets/products/blue-jacket-anarkali-main.webp",
    "gallery": [
      "assets/products/blue-jacket-anarkali-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "anarkali",
    "categoryLabel": "Anarkalis",
    "badge": "Jacket Anarkali",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "rani-lotus-anarkali",
    "name": "Rani Lotus Anarkali",
    "price": 13000,
    "color": "Rani Pink",
    "category": "anarkalis",
    "label": "Lotus Anarkali",
    "page_main": 9,
    "tone": "#c21766",
    "accent": "#18a0a2",
    "description": "A rani pink lotus anarkali with soft ethnic motifs and an elegant dupatta styling.",
    "fabric": "Rani anarkali with lotus-inspired embroidery, pants and dupatta.",
    "image": "assets/products/rani-lotus-anarkali-main.webp",
    "gallery": [
      "assets/products/rani-lotus-anarkali-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "anarkali",
    "categoryLabel": "Anarkalis",
    "badge": "Lotus Anarkali",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "grey-anarkali",
    "name": "Grey Anarkali",
    "price": 21000,
    "color": "Grey",
    "category": "anarkalis",
    "label": "Anarkali",
    "page_main": 10,
    "tone": "#bcc0c0",
    "accent": "#d38b61",
    "description": "A calm grey anarkali with refined embroidery and a soft festive dupatta.",
    "fabric": "Grey anarkali with subtle work, sheer dupatta and occasion-ready flare.",
    "image": "assets/products/grey-anarkali-main.webp",
    "gallery": [
      "assets/products/grey-anarkali-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "anarkali",
    "categoryLabel": "Anarkalis",
    "badge": "Anarkali",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "golden-drape",
    "name": "Golden Drape Set",
    "price": 11000,
    "color": "Golden",
    "category": "drapes",
    "label": "Drape Set",
    "page_main": 12,
    "tone": "#dcc28a",
    "accent": "#b78b4a",
    "description": "A minimal golden drape set with delicate handwork for intimate festive occasions.",
    "fabric": "Golden draped two-piece look with embellished blouse and flowing lower.",
    "image": "assets/products/golden-drape-main.webp",
    "gallery": [
      "assets/products/golden-drape-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "rakhi-drapes",
    "categoryLabel": "Drape Sets",
    "badge": "Drape Set",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "white-drape-saree",
    "name": "White Drape Saree",
    "price": 18000,
    "color": "White",
    "category": "drapes",
    "label": "Drape Saree",
    "page_main": 13,
    "tone": "#f4eee3",
    "accent": "#b78b4a",
    "description": "A clean white drape saree with tonal blouse texture for modern festive dressing.",
    "fabric": "White drape saree with tonal embellished blouse and pre-draped ease.",
    "image": "assets/products/white-drape-saree-main.webp",
    "gallery": [
      "assets/products/white-drape-saree-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "drape-saree",
    "categoryLabel": "Drape Sets",
    "badge": "Drape Saree",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "green-cape",
    "name": "Green Cape Set",
    "price": 18000,
    "color": "Green",
    "category": "festive",
    "label": "Cape Set",
    "page_main": 14,
    "tone": "#b7ead9",
    "accent": "#3b7f79",
    "description": "A fresh green cape set with embellished pants and a sheer layer for a contemporary Indian look.",
    "fabric": "Green cape co-ord with embellished trousers, crop top and flowy overlay.",
    "image": "assets/products/green-cape-main.webp",
    "gallery": [
      "assets/products/green-cape-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "cape",
    "categoryLabel": "Festive Wear",
    "badge": "Cape Set",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "wine-kurta-dhoti",
    "name": "Wine Kurta Dhoti",
    "price": 18000,
    "color": "Wine",
    "category": "festive",
    "label": "Kurta Dhoti",
    "page_main": 15,
    "tone": "#8c183b",
    "accent": "#d09952",
    "description": "A wine kurta dhoti set with rich neckline embroidery and asymmetrical festive styling.",
    "fabric": "Wine kurta with dhoti-style lower and embroidered yoke detailing.",
    "image": "assets/products/wine-kurta-dhoti-main.webp",
    "gallery": [
      "assets/products/wine-kurta-dhoti-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "kurta-dhoti",
    "categoryLabel": "Festive Wear",
    "badge": "Kurta Dhoti",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "celebrity-red",
    "name": "Red Celebrity Edit",
    "price": 15500,
    "color": "Red",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 2,
    "tone": "#c9203b",
    "accent": "#d5a25b",
    "description": "A statement red festive look from the celebrity-inspired Fable edit, styled for intimate celebrations and modern Indian occasions.",
    "fabric": "Festive Indian silhouette with refined embroidery and celebration-ready styling.",
    "subCategory": "celebrity-edit",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Celebrity Edit",
    "image": "assets/products/celebrity-red-main.webp",
    "gallery": [
      "assets/products/celebrity-red-main.webp",
      "assets/products/celebrity-red-detail-1.webp",
      "assets/products/celebrity-red-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 3
  },
  {
    "id": "celebrity-golden",
    "name": "Golden Celebrity Edit",
    "price": 15500,
    "color": "Golden",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 4,
    "tone": "#b99874",
    "accent": "#8b2742",
    "description": "A golden festive look with a soft traditional finish, made for bright occasions and elegant family functions.",
    "fabric": "Golden-toned festive ensemble with graceful drape and hand-finished detailing.",
    "subCategory": "celebrity-edit",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Celebrity Edit",
    "image": "assets/products/celebrity-golden-main.webp",
    "gallery": [
      "assets/products/celebrity-golden-main.webp",
      "assets/products/celebrity-golden-detail-1.webp",
      "assets/products/celebrity-golden-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 5
  },
  {
    "id": "celebrity-green-lehenga",
    "name": "Green Lehenga",
    "price": 45000,
    "color": "Green",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 6,
    "tone": "#184a37",
    "accent": "#c89c5d",
    "description": "A premium green lehenga look with rich festive styling and a couture-inspired finish.",
    "fabric": "Lehenga-style festive ensemble with ornate work and structured occasion wear appeal.",
    "subCategory": "lehenga",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Lehenga",
    "image": "assets/products/celebrity-green-lehenga-main.webp",
    "gallery": [
      "assets/products/celebrity-green-lehenga-main.webp",
      "assets/products/celebrity-green-lehenga-detail-1.webp",
      "assets/products/celebrity-green-lehenga-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 7
  },
  {
    "id": "celebrity-banarasi",
    "name": "Banarasi Heritage Look",
    "price": 75000,
    "color": "Banarasi",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 8,
    "tone": "#694884",
    "accent": "#7a1d36",
    "description": "A luxurious Banarasi-inspired look with a heritage mood, elevated for wedding and festive appearances.",
    "fabric": "Banarasi-inspired festive fabric with rich texture and premium Indian craftsmanship.",
    "subCategory": "heritage",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Banarasi",
    "image": "assets/products/celebrity-banarasi-main.webp",
    "gallery": [
      "assets/products/celebrity-banarasi-main.webp",
      "assets/products/celebrity-banarasi-detail-1.webp",
      "assets/products/celebrity-banarasi-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 9
  },
  {
    "id": "celebrity-golden-tissue",
    "name": "Golden Tissue Celebrity Look",
    "price": 19000,
    "color": "Golden Tissue",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 10,
    "tone": "#c9964b",
    "accent": "#b51d3d",
    "description": "A golden tissue festive edit with subtle shine and easy elegance for parties and family events.",
    "fabric": "Light golden tissue styling with soft shimmer and festive detail work.",
    "subCategory": "tissue",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Tissue Edit",
    "image": "assets/products/celebrity-golden-tissue-main.webp",
    "gallery": [
      "assets/products/celebrity-golden-tissue-main.webp",
      "assets/products/celebrity-golden-tissue-detail-1.webp",
      "assets/products/celebrity-golden-tissue-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 11
  },
  {
    "id": "celebrity-wine-kurta",
    "name": "Wine Kurta",
    "price": 17000,
    "color": "Wine",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 12,
    "tone": "#7c1838",
    "accent": "#d2a15c",
    "description": "A wine kurta look with deep festive colour and a refined embroidered neckline.",
    "fabric": "Wine-toned kurta silhouette with occasion-ready handwork and fluid styling.",
    "subCategory": "kurta",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Kurta Set",
    "image": "assets/products/celebrity-wine-kurta-main.webp",
    "gallery": [
      "assets/products/celebrity-wine-kurta-main.webp",
      "assets/products/celebrity-wine-kurta-detail-1.webp",
      "assets/products/celebrity-wine-kurta-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 13
  },
  {
    "id": "celebrity-beige",
    "name": "Beige Festive Edit",
    "price": 17000,
    "color": "Beige",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 14,
    "tone": "#e6cfaa",
    "accent": "#1e405f",
    "description": "A beige festive piece with an understated palette and premium styling for day-to-evening occasions.",
    "fabric": "Beige-toned Indian wear with soft detailing and modern festive comfort.",
    "subCategory": "festive",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Festive Edit",
    "image": "assets/products/celebrity-beige-main.webp",
    "gallery": [
      "assets/products/celebrity-beige-main.webp",
      "assets/products/celebrity-beige-detail-1.webp",
      "assets/products/celebrity-beige-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 15
  },
  {
    "id": "celebrity-multi-25000",
    "name": "Multi Festive Look",
    "price": 25000,
    "color": "Multi",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 16,
    "tone": "#b97a58",
    "accent": "#1b8b94",
    "description": "A multi-toned festive look with statement colour blocking and occasion-ready appeal.",
    "fabric": "Multi-colour festive ensemble with Indian motifs and soft dress-up detailing.",
    "subCategory": "multi",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Multi Edit",
    "image": "assets/products/celebrity-multi-25000-main.webp",
    "gallery": [
      "assets/products/celebrity-multi-25000-main.webp",
      "assets/products/celebrity-multi-25000-detail-1.webp",
      "assets/products/celebrity-multi-25000-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 17
  },
  {
    "id": "celebrity-blue",
    "name": "Blue Celebrity Edit",
    "price": 17000,
    "color": "Blue",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 18,
    "tone": "#1c977b",
    "accent": "#b82c3e",
    "description": "A blue festive look designed with easy elegance, detailed accents and celebration styling.",
    "fabric": "Blue Indian wear silhouette with embroidered or printed accent work.",
    "subCategory": "celebrity-edit",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Blue Edit",
    "image": "assets/products/celebrity-blue-main.webp",
    "gallery": [
      "assets/products/celebrity-blue-main.webp",
      "assets/products/celebrity-blue-detail-1.webp",
      "assets/products/celebrity-blue-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 19
  },
  {
    "id": "celebrity-red-jewellery-work",
    "name": "Red Jewellery Work Look",
    "price": 11000,
    "color": "Red",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 20,
    "tone": "#e33932",
    "accent": "#caa05e",
    "description": "A red look with jewellery-inspired detailing, designed for compact festive styling and special occasions.",
    "fabric": "Red festive ensemble with jewellery-style embroidery and ornate accents.",
    "subCategory": "jewellery-work",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Jewellery Work",
    "image": "assets/products/celebrity-red-jewellery-work-main.webp",
    "gallery": [
      "assets/products/celebrity-red-jewellery-work-main.webp",
      "assets/products/celebrity-red-jewellery-work-detail-1.webp",
      "assets/products/celebrity-red-jewellery-work-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 21
  },
  {
    "id": "celebrity-multi-11000",
    "name": "Multi Everyday Festive Look",
    "price": 11000,
    "color": "Multi",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 22,
    "tone": "#258b68",
    "accent": "#396d5b",
    "description": "A light multi-toned festive look for easy styling, family occasions and celebratory day wear.",
    "fabric": "Multi-toned Indian wear with soft handcrafted details and wearable festive finish.",
    "subCategory": "multi",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Multi Edit",
    "image": "assets/products/celebrity-multi-11000-main.webp",
    "gallery": [
      "assets/products/celebrity-multi-11000-main.webp",
      "assets/products/celebrity-multi-11000-detail-1.webp",
      "assets/products/celebrity-multi-11000-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 23
  }
];
