window.FABLE_PRODUCTS = [
  {
    "id": "teal-embroidered-drape-set",
    "name": "Teal Embroidered Drape Set",
    "price": 9500,
    "color": "Teal",
    "category": "drapes",
    "categoryLabel": "Drape Sets",
    "badge": "AI Model Edit",
    "tone": "#4f7480",
    "accent": "#c8d9dd",
    "description": "A teal draped co-ord set with a delicate embellished top and a softly cascading front drape.",
    "fabric": "Contemporary teal drape set with sheer embroidery, fluid pleating and a graceful festive silhouette.",
    "source": "New product upload + AI model styling",
    "subCategory": "ai-model-drapes",
    "image": "assets/products/teal-embroidered-drape-set-main.webp",
    "gallery": [
      "assets/products/teal-embroidered-drape-set-main.webp",
      "assets/products/teal-embroidered-drape-set-original.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "silver-beaded-one-shoulder-gown",
    "name": "Silver Beaded One-Shoulder Gown",
    "price": 9500,
    "color": "Silver",
    "category": "festive",
    "categoryLabel": "Festive Wear",
    "badge": "AI Model Edit",
    "tone": "#bfb6bc",
    "accent": "#ece4ea",
    "description": "A silver beaded one-shoulder gown with sculpted floral detailing and an elongated occasion silhouette.",
    "fabric": "Shimmering embellished gown with a statement neck flower, soft net texture and an elegant evening drape.",
    "source": "New product upload + AI model styling",
    "subCategory": "ai-model-festive",
    "image": "assets/products/silver-beaded-one-shoulder-gown-main.webp",
    "gallery": [
      "assets/products/silver-beaded-one-shoulder-gown-main.webp",
      "assets/products/silver-beaded-one-shoulder-gown-original.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "ivory-lace-tiered-dress",
    "name": "Ivory Lace Tiered Dress",
    "price": 9500,
    "color": "Ivory Lace",
    "category": "dresses",
    "categoryLabel": "Dresses",
    "badge": "AI Model Edit",
    "tone": "#f2ebe1",
    "accent": "#d9c8b7",
    "description": "An ivory lace dress with tiered layers, soft ruffles and a romantic boho-inspired silhouette.",
    "fabric": "Textured lace dress with tasseled sleeves, layered skirt panels and airy occasion movement.",
    "source": "New product upload + AI model styling",
    "subCategory": "ai-model-dresses",
    "image": "assets/products/ivory-lace-tiered-dress-main.webp",
    "gallery": [
      "assets/products/ivory-lace-tiered-dress-main.webp",
      "assets/products/ivory-lace-tiered-dress-original.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "red-embellished-draped-gown",
    "name": "Red Embellished Draped Gown",
    "price": 9500,
    "color": "Ruby Red",
    "category": "festive",
    "categoryLabel": "Festive Wear",
    "badge": "AI Model Edit",
    "tone": "#c41f2d",
    "accent": "#8f1a22",
    "description": "A dramatic ruby red draped gown with embellished bodice detailing and fluid cape-inspired sleeves.",
    "fabric": "Statement festive drape with rich embellishment, flowing sleeves and a sculpted ruched lower silhouette.",
    "source": "New product upload + AI model styling",
    "subCategory": "ai-model-festive",
    "image": "assets/products/red-embellished-draped-gown-main.webp",
    "gallery": [
      "assets/products/red-embellished-draped-gown-main.webp",
      "assets/products/red-embellished-draped-gown-original.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "white-botanical-asymmetric-dress",
    "name": "White Botanical Asymmetric Dress",
    "price": 7500,
    "color": "White Botanical",
    "category": "dresses",
    "categoryLabel": "Dresses",
    "badge": "New Dress Edit",
    "tone": "#f4efe8",
    "accent": "#1d1d1d",
    "description": "A crisp white shirt-style dress with black botanical line art and an asymmetric layered fall.",
    "fabric": "Structured white dress with collar, contrast line embroidery and an asymmetric hemline.",
    "source": "New product upload + AI model styling",
    "subCategory": "new-dresses",
    "image": "assets/products/white-botanical-asymmetric-dress-main.webp",
    "gallery": [
      "assets/products/white-botanical-asymmetric-dress-main.webp",
      "assets/products/white-botanical-asymmetric-dress-original.webp",
      "assets/products/white-botanical-asymmetric-dress-detail-1.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "lavender-sheer-coord-set",
    "name": "Lavender Sheer Co-ord Set",
    "price": 7500,
    "color": "Lavender",
    "category": "dresses",
    "categoryLabel": "Dresses",
    "badge": "New Dress Edit",
    "tone": "#b8b1f4",
    "accent": "#7e77d2",
    "description": "A soft lavender co-ord set with a cropped shirt-style top, sheer sleeves and a flowing grid-panel skirt.",
    "fabric": "Light lavender co-ord with organza-style skirt panels, soft transparency and shirt collar detailing.",
    "source": "New product upload + AI model styling",
    "subCategory": "new-dresses",
    "image": "assets/products/lavender-sheer-coord-set-main.webp",
    "gallery": [
      "assets/products/lavender-sheer-coord-set-main.webp",
      "assets/products/lavender-sheer-coord-set-original.webp",
      "assets/products/lavender-sheer-coord-set-detail-1.webp",
      "assets/products/lavender-sheer-coord-set-detail-2.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "plum-embroidered-cape-dress",
    "name": "Plum Embroidered Cape Dress",
    "price": 7500,
    "color": "Plum",
    "category": "dresses",
    "categoryLabel": "Dresses",
    "badge": "New Dress Edit",
    "tone": "#56306d",
    "accent": "#e7d4ef",
    "description": "A deep plum flared dress finished with an embroidered cape-style yoke for a graceful occasion look.",
    "fabric": "Flared plum silhouette with embroidered upper layer and soft festive movement.",
    "source": "New product upload + AI model styling",
    "subCategory": "new-dresses",
    "image": "assets/products/plum-embroidered-cape-dress-main.webp",
    "gallery": [
      "assets/products/plum-embroidered-cape-dress-main.webp",
      "assets/products/plum-embroidered-cape-dress-original.webp",
      "assets/products/plum-embroidered-cape-dress-detail-1.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "pastel-yellow-chiffon-set",
    "name": "Pastel Yellow Chiffon Set",
    "price": 7500,
    "color": "Pastel Yellow",
    "category": "dresses",
    "categoryLabel": "Dresses",
    "badge": "New Dress Edit",
    "tone": "#f4e8a8",
    "accent": "#2f67a8",
    "description": "A pastel yellow layered set with a floral embroidered collar, blue button accents and a breezy sheer skirt.",
    "fabric": "Soft pastel co-ord with sheer layering, embroidered collar and lightweight festive finish.",
    "source": "New product upload + AI model styling",
    "subCategory": "new-dresses",
    "image": "assets/products/pastel-yellow-chiffon-set-main.webp",
    "gallery": [
      "assets/products/pastel-yellow-chiffon-set-main.webp",
      "assets/products/pastel-yellow-chiffon-set-original.webp",
      "assets/products/pastel-yellow-chiffon-set-detail-1.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "fuchsia-ruffle-coord-set",
    "name": "Fuchsia Ruffle Co-ord Set",
    "price": 7500,
    "color": "Fuchsia",
    "category": "dresses",
    "categoryLabel": "Dresses",
    "badge": "New Dress Edit",
    "tone": "#e91d74",
    "accent": "#be145d",
    "description": "A vibrant fuchsia co-ord set with a ruched wrap-style top and flowing asymmetric ruffle skirt.",
    "fabric": "Bright fuchsia two-piece look with soft sheer sleeves, pleated bodice and ruffled skirt hem.",
    "source": "New product upload + AI model styling",
    "subCategory": "new-dresses",
    "image": "assets/products/fuchsia-ruffle-coord-set-main.webp",
    "gallery": [
      "assets/products/fuchsia-ruffle-coord-set-main.webp",
      "assets/products/fuchsia-ruffle-coord-set-original.webp",
      "assets/products/fuchsia-ruffle-coord-set-detail-1.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "mauve-lime-asymmetric-dress",
    "name": "Mauve Lime Asymmetric Dress",
    "price": 7500,
    "color": "Mauve Lime",
    "category": "dresses",
    "categoryLabel": "Dresses",
    "badge": "New Dress Edit",
    "tone": "#b9859a",
    "accent": "#82a84a",
    "description": "A playful mauve and lime color-block dress with a teal collar, short sleeves and an asymmetric skirt fall.",
    "fabric": "Contemporary color-block dress with shirt collar, contrast trims and asymmetric movement.",
    "source": "New product upload",
    "subCategory": "new-dresses",
    "image": "assets/products/mauve-lime-asymmetric-dress-main.webp",
    "gallery": [
      "assets/products/mauve-lime-asymmetric-dress-main.webp",
      "assets/products/mauve-lime-asymmetric-dress-original.webp",
      "assets/products/mauve-lime-asymmetric-dress-detail-1.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "grey-red-belted-dress",
    "name": "Grey Red Belted Dress",
    "price": 7500,
    "color": "Grey Red",
    "category": "dresses",
    "categoryLabel": "Dresses",
    "badge": "New Dress Edit",
    "tone": "#b9b1aa",
    "accent": "#c3192d",
    "description": "A clean grey, black and red paneled dress with a waist belt and contrast seam detailing.",
    "fabric": "Paneled dress with soft waist definition, contrast stitching and modern everyday festive styling.",
    "source": "New product upload",
    "subCategory": "new-dresses",
    "image": "assets/products/grey-red-belted-dress-main.webp",
    "gallery": [
      "assets/products/grey-red-belted-dress-main.webp",
      "assets/products/grey-red-belted-dress-original.webp",
      "assets/products/grey-red-belted-dress-detail-1.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "rust-ivory-panel-dress",
    "name": "Rust Ivory Panel Dress",
    "price": 7500,
    "color": "Rust Ivory",
    "category": "dresses",
    "categoryLabel": "Dresses",
    "badge": "New Dress Edit",
    "tone": "#c87a44",
    "accent": "#7f6655",
    "description": "A rust, ivory and taupe paneled midi dress with short puff sleeves and a soft sculpted shape.",
    "fabric": "Color-block midi silhouette with soft sleeves, curved paneling and relaxed festive elegance.",
    "source": "New product upload",
    "subCategory": "new-dresses",
    "image": "assets/products/rust-ivory-panel-dress-main.webp",
    "gallery": [
      "assets/products/rust-ivory-panel-dress-main.webp",
      "assets/products/rust-ivory-panel-dress-original.webp",
      "assets/products/rust-ivory-panel-dress-detail-1.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "red-grey-ombre-shirt-dress",
    "name": "Red Grey Ombre Shirt Dress",
    "price": 7500,
    "color": "Red Grey",
    "category": "dresses",
    "categoryLabel": "Dresses",
    "badge": "New Dress Edit",
    "tone": "#d42f42",
    "accent": "#85817a",
    "description": "A red-to-grey shirt dress finished with sheer black floral sleeves for a bold contemporary look.",
    "fabric": "Long shirt-dress silhouette with soft ombre effect and floral sheer sleeve detailing.",
    "source": "New product upload",
    "subCategory": "new-dresses",
    "image": "assets/products/red-grey-ombre-shirt-dress-main.webp",
    "gallery": [
      "assets/products/red-grey-ombre-shirt-dress-main.webp",
      "assets/products/red-grey-ombre-shirt-dress-original.webp",
      "assets/products/red-grey-ombre-shirt-dress-detail-1.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "grey-floral-sleeve-dress",
    "name": "Grey Floral Sleeve Dress",
    "price": 7500,
    "color": "Soft Grey",
    "category": "dresses",
    "categoryLabel": "Dresses",
    "badge": "New Dress Edit",
    "tone": "#b8aaa5",
    "accent": "#171313",
    "description": "A soft grey midi dress with black sheer floral sleeves and a clean collared front.",
    "fabric": "Minimal grey dress with sheer floral sleeves, collared neckline and easy A-line fall.",
    "source": "New product upload",
    "subCategory": "new-dresses",
    "image": "assets/products/grey-floral-sleeve-dress-main.webp",
    "gallery": [
      "assets/products/grey-floral-sleeve-dress-main.webp",
      "assets/products/grey-floral-sleeve-dress-original.webp",
      "assets/products/grey-floral-sleeve-dress-detail-1.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "white-blue-floral-dress",
    "name": "White Blue Floral Dress",
    "price": 9500,
    "color": "White Blue Floral",
    "category": "dresses",
    "categoryLabel": "Dresses",
    "badge": "AI Model Edit",
    "tone": "#f1e7d7",
    "accent": "#2b76b6",
    "description": "A sleeveless white dress with a blue floral statement motif, green stem work and orange flower accents.",
    "fabric": "Light floral dress with botanical appliqué-inspired artwork and a soft A-line shape.",
    "source": "New product upload + AI model styling",
    "subCategory": "ai-model-dresses",
    "image": "assets/products/white-blue-floral-dress-main.webp",
    "gallery": [
      "assets/products/white-blue-floral-dress-main.webp",
      "assets/products/white-blue-floral-dress-original.webp",
      "assets/products/white-blue-floral-dress-detail-1.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "white-black-floral-wrap-dress",
    "name": "White Black Floral Wrap Dress",
    "price": 9500,
    "color": "White Black Floral",
    "category": "dresses",
    "categoryLabel": "Dresses",
    "badge": "AI Model Edit",
    "tone": "#efe7dd",
    "accent": "#181616",
    "description": "A white wrap-style dress with a bold black floral artwork across the skirt and a clean waist tie.",
    "fabric": "Wrap dress silhouette with shirt collar, waist tie and oversized botanical placement artwork.",
    "source": "New product upload + AI model styling",
    "subCategory": "ai-model-dresses",
    "image": "assets/products/white-black-floral-wrap-dress-main.webp",
    "gallery": [
      "assets/products/white-black-floral-wrap-dress-main.webp",
      "assets/products/white-black-floral-wrap-dress-original.webp",
      "assets/products/white-black-floral-wrap-dress-detail-1.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "ivory-ruffle-hem-dress",
    "name": "Ivory Ruffle Hem Dress",
    "price": 9500,
    "color": "Ivory",
    "category": "dresses",
    "categoryLabel": "Dresses",
    "badge": "AI Model Edit",
    "tone": "#f4eee6",
    "accent": "#d7c5aa",
    "description": "A minimalist ivory sleeveless dress finished with sculptural floral ruffles along the asymmetric hem.",
    "fabric": "Clean ivory dress with a soft straight fall and textured 3D floral hem detailing.",
    "source": "New product upload + AI model styling",
    "subCategory": "ai-model-dresses",
    "image": "assets/products/ivory-ruffle-hem-dress-main.webp",
    "gallery": [
      "assets/products/ivory-ruffle-hem-dress-main.webp",
      "assets/products/ivory-ruffle-hem-dress-original.webp",
      "assets/products/ivory-ruffle-hem-dress-detail-1.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "color-block-zip-dress",
    "name": "Color Block Zip Dress",
    "price": 9500,
    "color": "Ivory Multi",
    "category": "dresses",
    "categoryLabel": "Dresses",
    "badge": "AI Model Edit",
    "tone": "#f0e3d4",
    "accent": "#823128",
    "description": "A collared ivory dress with a zip neckline, rolled sleeves and bold red, plum and green color blocking.",
    "fabric": "Linen-feel modern dress with zip-front detail, pockets and contrast geometric panels.",
    "source": "New product upload + AI model styling",
    "subCategory": "ai-model-dresses",
    "image": "assets/products/color-block-zip-dress-main.webp",
    "gallery": [
      "assets/products/color-block-zip-dress-main.webp",
      "assets/products/color-block-zip-dress-original.webp",
      "assets/products/color-block-zip-dress-detail-1.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "ivory-printed-ruffle-dress",
    "name": "Ivory Printed Ruffle Dress",
    "price": 9500,
    "color": "Ivory Print",
    "category": "dresses",
    "categoryLabel": "Dresses",
    "badge": "AI Model Edit",
    "tone": "#f3e8d8",
    "accent": "#62564b",
    "description": "An ivory sleeveless dress with a ruffled front placket and a gathered skirt with delicate printed motifs.",
    "fabric": "Soft ivory dress with ruffled neckline, cinched waist and light printed flared skirt.",
    "source": "New product upload + AI model styling",
    "subCategory": "ai-model-dresses",
    "image": "assets/products/ivory-printed-ruffle-dress-main.webp",
    "gallery": [
      "assets/products/ivory-printed-ruffle-dress-main.webp",
      "assets/products/ivory-printed-ruffle-dress-original.webp",
      "assets/products/ivory-printed-ruffle-dress-detail-1.webp"
    ],
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "blue",
    "name": "Blue Signature Saree",
    "price": 35000,
    "color": "Blue",
    "category": "sarees",
    "label": "Signature Edit",
    "page_main": 2,
    "page_detail": 3,
    "tone": "#34206f",
    "accent": "#d7ba61",
    "description": "A royal blue drape paired with a golden blouse and ornate floral border work for evening celebrations.",
    "fabric": "Flowing festive drape with embellished blouse and embroidered border.",
    "image": "assets/products/blue-main.webp",
    "gallery": [
      "assets/products/blue-main.webp",
      "assets/products/blue-detail-1.webp",
      "assets/products/blue-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "signature",
    "categoryLabel": "Sarees",
    "badge": "Signature Edit",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "golden-tissue",
    "name": "Golden Tissue Saree",
    "price": 25000,
    "color": "Golden Tissue",
    "category": "sarees",
    "label": "Tissue Sarees",
    "page_main": 4,
    "page_detail": 5,
    "tone": "#c9a36a",
    "accent": "#9d3158",
    "description": "A luminous golden tissue saree with soft rose undertones, floral handwork and a contrast magenta finish.",
    "fabric": "Tissue finish saree with floral embroidery and festive blouse detailing.",
    "image": "assets/products/golden-tissue-main.webp",
    "gallery": [
      "assets/products/golden-tissue-main.webp",
      "assets/products/golden-tissue-detail-1.webp",
      "assets/products/golden-tissue-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "tissue",
    "categoryLabel": "Sarees",
    "badge": "Tissue Sarees",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "orange",
    "name": "Orange Festive Saree",
    "price": 30000,
    "color": "Orange",
    "category": "sarees",
    "label": "Festive Sarees",
    "page_main": 6,
    "page_detail": 7,
    "tone": "#c95225",
    "accent": "#111111",
    "description": "A warm orange drape contrasted with a black heavily worked blouse for bold festive styling.",
    "fabric": "Sheer festive drape with contrast embellished blouse and delicate border.",
    "image": "assets/products/orange-main.webp",
    "gallery": [
      "assets/products/orange-main.webp",
      "assets/products/orange-detail-1.webp",
      "assets/products/orange-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "festive",
    "categoryLabel": "Sarees",
    "badge": "Festive Sarees",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "shreenathji",
    "name": "Shreenathji Art Saree",
    "price": 42000,
    "color": "Shreenathji",
    "category": "sarees",
    "label": "Heritage Art",
    "page_main": 8,
    "page_detail": 9,
    "tone": "#bce3dd",
    "accent": "#b14461",
    "description": "A sea-green saree with temple-inspired art motifs, peacock detailing and a rich pink blouse.",
    "fabric": "Art-inspired embroidered saree with narrative motifs and ornate blouse work.",
    "image": "assets/products/shreenathji-main.webp",
    "gallery": [
      "assets/products/shreenathji-main.webp",
      "assets/products/shreenathji-detail-1.webp",
      "assets/products/shreenathji-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "heritage",
    "categoryLabel": "Sarees",
    "badge": "Heritage Art",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "lavender",
    "name": "Lavender Jewel Saree",
    "price": 35000,
    "color": "Lavender",
    "category": "sarees",
    "label": "Signature Edit",
    "page_main": 10,
    "page_detail": 11,
    "tone": "#c6a6d7",
    "accent": "#a41746",
    "description": "A soft lavender drape styled with jewel embellishments and a deep rose blouse for reception-ready elegance.",
    "fabric": "Soft sheer drape with gemstone-style border work and statement blouse details.",
    "image": "assets/products/lavender-main.webp",
    "gallery": [
      "assets/products/lavender-main.webp",
      "assets/products/lavender-detail-1.webp",
      "assets/products/lavender-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "signature",
    "categoryLabel": "Sarees",
    "badge": "Signature Edit",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "silver-tissue",
    "name": "Silver Tissue Saree",
    "price": 30000,
    "color": "Silver Tissue",
    "category": "sarees",
    "label": "Tissue Sarees",
    "page_main": 12,
    "page_detail": 13,
    "tone": "#d8d2c8",
    "accent": "#38206d",
    "description": "A refined silver tissue saree accented with blue blouse embroidery and umbrella-inspired border motifs.",
    "fabric": "Silver tissue drape with blue embroidered blouse and textural finish.",
    "image": "assets/products/silver-tissue-main.webp",
    "gallery": [
      "assets/products/silver-tissue-main.webp",
      "assets/products/silver-tissue-detail-1.webp",
      "assets/products/silver-tissue-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "tissue",
    "categoryLabel": "Sarees",
    "badge": "Tissue Sarees",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "green",
    "name": "Green Floral Saree",
    "price": 30000,
    "color": "Green",
    "category": "sarees",
    "label": "Festive Sarees",
    "page_main": 14,
    "page_detail": 15,
    "tone": "#cdd8bf",
    "accent": "#dd91a7",
    "description": "A pastel green saree with soft floral embroidery and graceful tasseled border accents.",
    "fabric": "Pastel festive drape with floral embroidery, bead details and blouse artistry.",
    "image": "assets/products/green-main.webp",
    "gallery": [
      "assets/products/green-main.webp",
      "assets/products/green-detail-1.webp",
      "assets/products/green-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "festive",
    "categoryLabel": "Sarees",
    "badge": "Festive Sarees",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "black",
    "name": "Black Couture Saree",
    "price": 42000,
    "color": "Black",
    "category": "sarees",
    "label": "Heritage Art",
    "page_main": 16,
    "page_detail": 17,
    "tone": "#0d0d16",
    "accent": "#70ad9d",
    "description": "A dramatic black saree styled with an embroidered couture jacket and metallic handwork.",
    "fabric": "Black statement drape with embellished blouse and ornate embroidered jacket.",
    "image": "assets/products/black-main.webp",
    "gallery": [
      "assets/products/black-main.webp",
      "assets/products/black-detail-1.webp",
      "assets/products/black-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "heritage",
    "categoryLabel": "Sarees",
    "badge": "Heritage Art",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "white-org",
    "name": "White Organza Saree",
    "price": 25000,
    "color": "White Organza",
    "category": "sarees",
    "label": "Organza Sarees",
    "page_main": 18,
    "page_detail": 19,
    "tone": "#f7f4ec",
    "accent": "#181820",
    "description": "A crisp white organza saree with bold black floral linework and a sculpted black blouse.",
    "fabric": "White organza drape with graphic floral embroidery and scalloped accents.",
    "image": "assets/products/white-org-main.webp",
    "gallery": [
      "assets/products/white-org-main.webp",
      "assets/products/white-org-detail-1.webp",
      "assets/products/white-org-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "organza",
    "categoryLabel": "Sarees",
    "badge": "Organza Sarees",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "sea-green",
    "name": "Sea Green Geometric Saree",
    "price": 35000,
    "color": "Sea Green",
    "category": "sarees",
    "label": "Organza Sarees",
    "page_main": 20,
    "page_detail": 21,
    "tone": "#aeb5a5",
    "accent": "#ee544f",
    "description": "A sea-green drape with delicate geometric embroidery, paired with a coral statement blouse.",
    "fabric": "Sheer sea-green drape with geometric handwork and contrast blouse.",
    "image": "assets/products/sea-green-main.webp",
    "gallery": [
      "assets/products/sea-green-main.webp",
      "assets/products/sea-green-detail-1.webp",
      "assets/products/sea-green-detail-2.webp"
    ],
    "source": "Saree Look Book by Fable",
    "subCategory": "organza",
    "categoryLabel": "Sarees",
    "badge": "Organza Sarees",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "purple-drape",
    "name": "Purple Drape Set",
    "price": 25000,
    "color": "Purple",
    "category": "drapes",
    "label": "Rakhi Drape",
    "page_main": 2,
    "tone": "#74299a",
    "accent": "#b78b4a",
    "description": "A striking purple drape set with ornate blouse work for a refined festive look.",
    "fabric": "Festive drape set with embroidered blouse and soft flowy lower drape.",
    "image": "assets/products/purple-drape-main.webp",
    "gallery": [
      "assets/products/purple-drape-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "rakhi-drapes",
    "categoryLabel": "Drape Sets",
    "badge": "Rakhi Drape",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "yellow-drape",
    "name": "Yellow Drape Set",
    "price": 17000,
    "color": "Yellow",
    "category": "drapes",
    "label": "Rakhi Drape",
    "page_main": 3,
    "tone": "#d7bf22",
    "accent": "#9b1e33",
    "description": "A sunshine yellow drape silhouette with a structured jacket-inspired top and festive movement.",
    "fabric": "Contemporary draped festive set with jacket detailing and layered lower.",
    "image": "assets/products/yellow-drape-main.webp",
    "gallery": [
      "assets/products/yellow-drape-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "rakhi-drapes",
    "categoryLabel": "Drape Sets",
    "badge": "Rakhi Drape",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "yellow-anarkali",
    "name": "Yellow Anarkali",
    "price": 19000,
    "color": "Yellow",
    "category": "anarkalis",
    "label": "Anarkali",
    "page_main": 4,
    "tone": "#bfa133",
    "accent": "#b53b57",
    "description": "A graceful yellow anarkali finished with rich embroidery and a deep rose dupatta.",
    "fabric": "Flowing anarkali with embroidered neckline and contrast festive dupatta.",
    "image": "assets/products/yellow-anarkali-main.webp",
    "gallery": [
      "assets/products/yellow-anarkali-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "anarkali",
    "categoryLabel": "Anarkalis",
    "badge": "Anarkali",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "peach-sharara",
    "name": "Peach Sharara Set",
    "price": 20000,
    "color": "Peach",
    "category": "festive",
    "label": "Sharara",
    "page_main": 5,
    "tone": "#efc0bd",
    "accent": "#d5a313",
    "description": "A soft peach sharara set styled with a tailored festive jacket and elegant fall.",
    "fabric": "Peach sharara set with jacket-style top, embroidery and wide-leg flow.",
    "image": "assets/products/peach-sharara-main.webp",
    "gallery": [
      "assets/products/peach-sharara-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "sharara",
    "categoryLabel": "Festive Wear",
    "badge": "Sharara",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "red-bandhej",
    "name": "Red Bandhej Set",
    "price": 35000,
    "color": "Red Bandhej",
    "category": "festive",
    "label": "Bandhej",
    "page_main": 6,
    "tone": "#cb1432",
    "accent": "#b78b4a",
    "description": "A rich red bandhej-inspired festive set with statement dupatta and gold accents.",
    "fabric": "Bandhej-style festive kurta set with embellished border and flowing dupatta.",
    "image": "assets/products/red-bandhej-main.webp",
    "gallery": [
      "assets/products/red-bandhej-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "bandhej",
    "categoryLabel": "Festive Wear",
    "badge": "Bandhej",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "beige-anarkali",
    "name": "Beige Anarkali",
    "price": 17000,
    "color": "Beige",
    "category": "anarkalis",
    "label": "Anarkali",
    "page_main": 7,
    "tone": "#ead3a7",
    "accent": "#0d5843",
    "description": "A soft beige anarkali with delicate drawstring details and understated festive elegance.",
    "fabric": "Light beige anarkali with dupatta, handmade tassels and soft border finish.",
    "image": "assets/products/beige-anarkali-main.webp",
    "gallery": [
      "assets/products/beige-anarkali-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "anarkali",
    "categoryLabel": "Anarkalis",
    "badge": "Anarkali",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "blue-jacket-anarkali",
    "name": "Blue Jacket Anarkali",
    "price": 18000,
    "color": "Blue",
    "category": "anarkalis",
    "label": "Jacket Anarkali",
    "page_main": 8,
    "tone": "#30446f",
    "accent": "#9b1e33",
    "description": "A blue anarkali elevated with a short embroidered jacket for a festive yet easy silhouette.",
    "fabric": "Blue anarkali with printed or embroidered jacket and tie-up detailing.",
    "image": "assets/products/blue-jacket-anarkali-main.webp",
    "gallery": [
      "assets/products/blue-jacket-anarkali-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "anarkali",
    "categoryLabel": "Anarkalis",
    "badge": "Jacket Anarkali",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "rani-lotus-anarkali",
    "name": "Rani Lotus Anarkali",
    "price": 13000,
    "color": "Rani Pink",
    "category": "anarkalis",
    "label": "Lotus Anarkali",
    "page_main": 9,
    "tone": "#c21766",
    "accent": "#18a0a2",
    "description": "A rani pink lotus anarkali with soft ethnic motifs and an elegant dupatta styling.",
    "fabric": "Rani anarkali with lotus-inspired embroidery, pants and dupatta.",
    "image": "assets/products/rani-lotus-anarkali-main.webp",
    "gallery": [
      "assets/products/rani-lotus-anarkali-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "anarkali",
    "categoryLabel": "Anarkalis",
    "badge": "Lotus Anarkali",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "grey-anarkali",
    "name": "Grey Anarkali",
    "price": 21000,
    "color": "Grey",
    "category": "anarkalis",
    "label": "Anarkali",
    "page_main": 10,
    "tone": "#bcc0c0",
    "accent": "#d38b61",
    "description": "A calm grey anarkali with refined embroidery and a soft festive dupatta.",
    "fabric": "Grey anarkali with subtle work, sheer dupatta and occasion-ready flare.",
    "image": "assets/products/grey-anarkali-main.webp",
    "gallery": [
      "assets/products/grey-anarkali-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "anarkali",
    "categoryLabel": "Anarkalis",
    "badge": "Anarkali",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "golden-drape",
    "name": "Golden Drape Set",
    "price": 11000,
    "color": "Golden",
    "category": "drapes",
    "label": "Drape Set",
    "page_main": 12,
    "tone": "#dcc28a",
    "accent": "#b78b4a",
    "description": "A minimal golden drape set with delicate handwork for intimate festive occasions.",
    "fabric": "Golden draped two-piece look with embellished blouse and flowing lower.",
    "image": "assets/products/golden-drape-main.webp",
    "gallery": [
      "assets/products/golden-drape-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "rakhi-drapes",
    "categoryLabel": "Drape Sets",
    "badge": "Drape Set",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "white-drape-saree",
    "name": "White Drape Saree",
    "price": 18000,
    "color": "White",
    "category": "drapes",
    "label": "Drape Saree",
    "page_main": 13,
    "tone": "#f4eee3",
    "accent": "#b78b4a",
    "description": "A clean white drape saree with tonal blouse texture for modern festive dressing.",
    "fabric": "White drape saree with tonal embellished blouse and pre-draped ease.",
    "image": "assets/products/white-drape-saree-main.webp",
    "gallery": [
      "assets/products/white-drape-saree-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "drape-saree",
    "categoryLabel": "Drape Sets",
    "badge": "Drape Saree",
    "sizes": [
      "Ready blouse",
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "green-cape",
    "name": "Green Cape Set",
    "price": 18000,
    "color": "Green",
    "category": "festive",
    "label": "Cape Set",
    "page_main": 14,
    "tone": "#b7ead9",
    "accent": "#3b7f79",
    "description": "A fresh green cape set with embellished pants and a sheer layer for a contemporary Indian look.",
    "fabric": "Green cape co-ord with embellished trousers, crop top and flowy overlay.",
    "image": "assets/products/green-cape-main.webp",
    "gallery": [
      "assets/products/green-cape-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "cape",
    "categoryLabel": "Festive Wear",
    "badge": "Cape Set",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "wine-kurta-dhoti",
    "name": "Wine Kurta Dhoti",
    "price": 18000,
    "color": "Wine",
    "category": "festive",
    "label": "Kurta Dhoti",
    "page_main": 15,
    "tone": "#8c183b",
    "accent": "#d09952",
    "description": "A wine kurta dhoti set with rich neckline embroidery and asymmetrical festive styling.",
    "fabric": "Wine kurta with dhoti-style lower and embroidered yoke detailing.",
    "image": "assets/products/wine-kurta-dhoti-main.webp",
    "gallery": [
      "assets/products/wine-kurta-dhoti-main.webp"
    ],
    "source": "RAKHI FABLE 2026",
    "subCategory": "kurta-dhoti",
    "categoryLabel": "Festive Wear",
    "badge": "Kurta Dhoti",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ]
  },
  {
    "id": "celebrity-red",
    "name": "Red Celebrity Edit",
    "price": 15500,
    "color": "Red",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 2,
    "tone": "#c9203b",
    "accent": "#d5a25b",
    "description": "A statement red festive look from the celebrity-inspired Fable edit, styled for intimate celebrations and modern Indian occasions.",
    "fabric": "Festive Indian silhouette with refined embroidery and celebration-ready styling.",
    "subCategory": "celebrity-edit",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Celebrity Edit",
    "image": "assets/celebrities/showcase/celebrity-red-main.webp",
    "gallery": [
      "assets/celebrities/showcase/celebrity-red-main.webp",
      "assets/celebrities/showcase/celebrity-red-detail-1.webp",
      "assets/celebrities/showcase/celebrity-red-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 3
  },
  {
    "id": "celebrity-golden",
    "name": "Golden Celebrity Edit",
    "price": 15500,
    "color": "Golden",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 4,
    "tone": "#b99874",
    "accent": "#8b2742",
    "description": "A golden festive look with a soft traditional finish, made for bright occasions and elegant family functions.",
    "fabric": "Golden-toned festive ensemble with graceful drape and hand-finished detailing.",
    "subCategory": "celebrity-edit",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Celebrity Edit",
    "image": "assets/celebrities/showcase/celebrity-golden-main.webp",
    "gallery": [
      "assets/celebrities/showcase/celebrity-golden-main.webp",
      "assets/celebrities/showcase/celebrity-golden-detail-1.webp",
      "assets/celebrities/showcase/celebrity-golden-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 5
  },
  {
    "id": "celebrity-green-lehenga",
    "name": "Green Lehenga",
    "price": 45000,
    "color": "Green",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 6,
    "tone": "#184a37",
    "accent": "#c89c5d",
    "description": "A premium green lehenga look with rich festive styling and a couture-inspired finish.",
    "fabric": "Lehenga-style festive ensemble with ornate work and structured occasion wear appeal.",
    "subCategory": "lehenga",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Lehenga",
    "image": "assets/celebrities/showcase/celebrity-green-lehenga-main.webp",
    "gallery": [
      "assets/celebrities/showcase/celebrity-green-lehenga-main.webp",
      "assets/celebrities/showcase/celebrity-green-lehenga-detail-1.webp",
      "assets/celebrities/showcase/celebrity-green-lehenga-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 7
  },
  {
    "id": "celebrity-banarasi",
    "name": "Banarasi Heritage Look",
    "price": 75000,
    "color": "Banarasi",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 8,
    "tone": "#694884",
    "accent": "#7a1d36",
    "description": "A luxurious Banarasi-inspired look with a heritage mood, elevated for wedding and festive appearances.",
    "fabric": "Banarasi-inspired festive fabric with rich texture and premium Indian craftsmanship.",
    "subCategory": "heritage",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Banarasi",
    "image": "assets/celebrities/showcase/celebrity-banarasi-main.webp",
    "gallery": [
      "assets/celebrities/showcase/celebrity-banarasi-main.webp",
      "assets/celebrities/showcase/celebrity-banarasi-detail-1.webp",
      "assets/celebrities/showcase/celebrity-banarasi-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 9
  },
  {
    "id": "celebrity-golden-tissue",
    "name": "Golden Tissue Celebrity Look",
    "price": 19000,
    "color": "Golden Tissue",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 10,
    "tone": "#c9964b",
    "accent": "#b51d3d",
    "description": "A golden tissue festive edit with subtle shine and easy elegance for parties and family events.",
    "fabric": "Light golden tissue styling with soft shimmer and festive detail work.",
    "subCategory": "tissue",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Tissue Edit",
    "image": "assets/celebrities/showcase/celebrity-golden-tissue-main.webp",
    "gallery": [
      "assets/celebrities/showcase/celebrity-golden-tissue-main.webp",
      "assets/celebrities/showcase/celebrity-golden-tissue-detail-1.webp",
      "assets/celebrities/showcase/celebrity-golden-tissue-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 11
  },
  {
    "id": "celebrity-wine-kurta",
    "name": "Wine Kurta",
    "price": 17000,
    "color": "Wine",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 12,
    "tone": "#7c1838",
    "accent": "#d2a15c",
    "description": "A wine kurta look with deep festive colour and a refined embroidered neckline.",
    "fabric": "Wine-toned kurta silhouette with occasion-ready handwork and fluid styling.",
    "subCategory": "kurta",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Kurta Set",
    "image": "assets/celebrities/showcase/celebrity-wine-kurta-main.webp",
    "gallery": [
      "assets/celebrities/showcase/celebrity-wine-kurta-main.webp",
      "assets/celebrities/showcase/celebrity-wine-kurta-detail-1.webp",
      "assets/celebrities/showcase/celebrity-wine-kurta-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 13
  },
  {
    "id": "celebrity-beige",
    "name": "Beige Festive Edit",
    "price": 17000,
    "color": "Beige",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 14,
    "tone": "#e6cfaa",
    "accent": "#1e405f",
    "description": "A beige festive piece with an understated palette and premium styling for day-to-evening occasions.",
    "fabric": "Beige-toned Indian wear with soft detailing and modern festive comfort.",
    "subCategory": "festive",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Festive Edit",
    "image": "assets/celebrities/showcase/celebrity-beige-main.webp",
    "gallery": [
      "assets/celebrities/showcase/celebrity-beige-main.webp",
      "assets/celebrities/showcase/celebrity-beige-detail-1.webp",
      "assets/celebrities/showcase/celebrity-beige-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 15
  },
  {
    "id": "celebrity-multi-25000",
    "name": "Multi Festive Look",
    "price": 25000,
    "color": "Multi",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 16,
    "tone": "#b97a58",
    "accent": "#1b8b94",
    "description": "A multi-toned festive look with statement colour blocking and occasion-ready appeal.",
    "fabric": "Multi-colour festive ensemble with Indian motifs and soft dress-up detailing.",
    "subCategory": "multi",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Multi Edit",
    "image": "assets/celebrities/showcase/celebrity-multi-25000-main.webp",
    "gallery": [
      "assets/celebrities/showcase/celebrity-multi-25000-main.webp",
      "assets/celebrities/showcase/celebrity-multi-25000-detail-1.webp",
      "assets/celebrities/showcase/celebrity-multi-25000-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 17
  },
  {
    "id": "celebrity-blue",
    "name": "Blue Celebrity Edit",
    "price": 17000,
    "color": "Blue",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 18,
    "tone": "#1c977b",
    "accent": "#b82c3e",
    "description": "A blue festive look designed with easy elegance, detailed accents and celebration styling.",
    "fabric": "Blue Indian wear silhouette with embroidered or printed accent work.",
    "subCategory": "celebrity-edit",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Blue Edit",
    "image": "assets/celebrities/showcase/celebrity-blue-main.webp",
    "gallery": [
      "assets/celebrities/showcase/celebrity-blue-main.webp",
      "assets/celebrities/showcase/celebrity-blue-detail-1.webp",
      "assets/celebrities/showcase/celebrity-blue-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 19
  },
  {
    "id": "celebrity-red-jewellery-work",
    "name": "Red Jewellery Work Look",
    "price": 11000,
    "color": "Red",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 20,
    "tone": "#e33932",
    "accent": "#caa05e",
    "description": "A red look with jewellery-inspired detailing, designed for compact festive styling and special occasions.",
    "fabric": "Red festive ensemble with jewellery-style embroidery and ornate accents.",
    "subCategory": "jewellery-work",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Jewellery Work",
    "image": "assets/celebrities/showcase/celebrity-red-jewellery-work-main.webp",
    "gallery": [
      "assets/celebrities/showcase/celebrity-red-jewellery-work-main.webp",
      "assets/celebrities/showcase/celebrity-red-jewellery-work-detail-1.webp",
      "assets/celebrities/showcase/celebrity-red-jewellery-work-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 21
  },
  {
    "id": "celebrity-multi-11000",
    "name": "Multi Everyday Festive Look",
    "price": 11000,
    "color": "Multi",
    "category": "celebrity",
    "label": "What Celebrities Wear",
    "page_main": 22,
    "tone": "#258b68",
    "accent": "#396d5b",
    "description": "A light multi-toned festive look for easy styling, family occasions and celebratory day wear.",
    "fabric": "Multi-toned Indian wear with soft handcrafted details and wearable festive finish.",
    "subCategory": "multi",
    "categoryLabel": "What Celebrities Wear",
    "badge": "Multi Edit",
    "image": "assets/celebrities/showcase/celebrity-multi-11000-main.webp",
    "gallery": [
      "assets/celebrities/showcase/celebrity-multi-11000-main.webp",
      "assets/celebrities/showcase/celebrity-multi-11000-detail-1.webp",
      "assets/celebrities/showcase/celebrity-multi-11000-detail-2.webp"
    ],
    "source": "New Look Book by Fable",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "Custom fit"
    ],
    "page_detail": 23
  }
];
