"use strict";

// Catalogue prices are sample website values. Replace them with the brand's final prices before launch.
window.FABLE_PRODUCTS = [
  {
    id: "crimson-drape-jacket",
    name: "Crimson Drape Jacket Set",
    category: "fusion",
    categoryLabel: "Fusion Edit",
    price: 14900,
    image: "assets/products/crimson-drape-jacket.webp",
    tone: "#f1d9da",
    badge: "New",
    sizes: ["S", "M", "L", "XL"],
    description: "A sculptural draped silhouette finished with a cropped jacket and richly embellished cuffs."
  },
  {
    id: "mocha-drape-jacket",
    name: "Mocha Drape Jacket Lehenga",
    category: "fusion",
    categoryLabel: "Fusion Edit",
    price: 16900,
    image: "assets/products/mocha-drape-jacket.webp",
    tone: "#e9dfdb",
    badge: "Fable Edit",
    sizes: ["S", "M", "L", "XL"],
    description: "Muted metallic tones, a fluid drape and a delicately detailed jacket create modern occasion dressing."
  },
  {
    id: "emerald-bandhani-lehenga",
    name: "Emerald Bandhani Lehenga",
    category: "lehengas",
    categoryLabel: "Lehengas",
    price: 18500,
    image: "assets/products/emerald-bandhani-lehenga.webp",
    tone: "#dce7df",
    badge: "Bestseller",
    sizes: ["S", "M", "L", "XL"],
    description: "A deep emerald festive lehenga paired with a vibrant bandhani-inspired drape and ornate borders."
  },
  {
    id: "royal-purple-lehenga",
    name: "Royal Purple Brocade Lehenga",
    category: "lehengas",
    categoryLabel: "Lehengas",
    price: 21900,
    image: "assets/products/royal-purple-lehenga.webp",
    tone: "#e3ddec",
    badge: "Occasion",
    sizes: ["S", "M", "L", "XL"],
    description: "A regal purple ensemble with luminous woven motifs and a contrasting red drape."
  },
  {
    id: "antique-gold-jacket-set",
    name: "Antique Gold Jacket Set",
    category: "fusion",
    categoryLabel: "Fusion Edit",
    price: 13700,
    image: "assets/products/antique-gold-jacket-set.webp",
    tone: "#eee2d0",
    badge: "Limited",
    sizes: ["S", "M", "L", "XL"],
    description: "An easy longline jacket set in an antique-gold palette, detailed with playful embroidered accents."
  },
  {
    id: "rani-embroidered-kurta",
    name: "Rani Embroidered Kurta Set",
    category: "kurta-sets",
    categoryLabel: "Kurta Sets",
    price: 9800,
    image: "assets/products/rani-embroidered-kurta.webp",
    tone: "#edd9df",
    badge: "Everyday Festive",
    sizes: ["S", "M", "L", "XL"],
    description: "A rich rani-pink kurta with an asymmetric hem and intricate multicolour neckline embroidery."
  },
  {
    id: "ivory-angrakha-set",
    name: "Ivory Angrakha Set",
    category: "kurta-sets",
    categoryLabel: "Kurta Sets",
    price: 11500,
    image: "assets/products/ivory-angrakha-set.webp",
    tone: "#f2eadb",
    badge: "Signature",
    sizes: ["S", "M", "L", "XL"],
    description: "A soft ivory wrap silhouette with delicate trims, tassels and an unexpected peacock-inspired detail."
  },
  {
    id: "rose-gold-anarkali",
    name: "Rose Gold Embroidered Anarkali",
    category: "lehengas",
    categoryLabel: "Celebration Sets",
    price: 17900,
    image: "assets/products/rose-gold-anarkali.webp",
    tone: "#f0ded8",
    badge: "Celebration",
    sizes: ["S", "M", "L", "XL"],
    description: "A flowing rose and antique-gold anarkali framed by an ornate embroidered bodice and sheer layers."
  },
  {
    id: "jade-embroidered-kurta",
    name: "Jade Embroidered Kurta Set",
    category: "kurta-sets",
    categoryLabel: "Kurta Sets",
    price: 9200,
    image: "assets/products/jade-embroidered-kurta.webp",
    tone: "#dce9e3",
    badge: "Easy Edit",
    sizes: ["S", "M", "L", "XL"],
    description: "A relaxed jade kurta with a soft handkerchief hem and delicate metallic embroidery."
  },
  {
    id: "vermilion-silk-kaftan",
    name: "Vermilion Kaftan Set",
    category: "kurta-sets",
    categoryLabel: "Kurta Sets",
    price: 8900,
    image: "assets/products/vermilion-silk-kaftan.webp",
    tone: "#f1d9d5",
    badge: "New Colour",
    sizes: ["S", "M", "L", "XL"],
    description: "A free-flowing vermilion silhouette lifted with delicate gold-toned motifs and an effortless drape."
  },
  {
    id: "emerald-magenta-set",
    name: "Emerald Magenta Colour-Block Set",
    category: "fusion",
    categoryLabel: "Fusion Edit",
    price: 9900,
    image: "assets/products/emerald-magenta-set.webp",
    tone: "#dde7df",
    badge: "Playful",
    sizes: ["S", "M", "L", "XL"],
    description: "A playful colour-blocked tunic set balancing jewel tones with a bold circular motif."
  },
  {
    id: "midnight-navy-saree",
    name: "Midnight Navy Draped Saree",
    category: "sarees",
    categoryLabel: "Sarees",
    price: 13200,
    image: "assets/products/midnight-navy-saree.webp",
    tone: "#dcddec",
    badge: "Draped Edit",
    sizes: ["Free Size"],
    description: "A deep navy drape paired with a mustard blouse and ornate floral embroidery."
  },
  {
    id: "taupe-rose-saree",
    name: "Taupe Rose Embroidered Saree",
    category: "sarees",
    categoryLabel: "Sarees",
    price: 14500,
    image: "assets/products/taupe-rose-saree.webp",
    tone: "#eadfdf",
    badge: "Hand Detail",
    sizes: ["Free Size"],
    description: "A luminous taupe saree with botanical embroidery and a rich rose-toned contrast lining."
  },
  {
    id: "burnt-orange-saree",
    name: "Burnt Orange Organza Saree",
    category: "sarees",
    categoryLabel: "Sarees",
    price: 13900,
    image: "assets/products/burnt-orange-saree.webp",
    tone: "#eeddd3",
    badge: "Statement",
    sizes: ["Free Size"],
    description: "A translucent burnt-orange drape paired with a densely embroidered black blouse."
  },
  {
    id: "mint-peacock-saree",
    name: "Mint Peacock Saree",
    category: "sarees",
    categoryLabel: "Sarees",
    price: 15100,
    image: "assets/products/mint-peacock-saree.webp",
    tone: "#ddeae5",
    badge: "Fable Favourite",
    sizes: ["Free Size"],
    description: "A calm mint saree with a contrasting rose blouse and playful peacock-inspired details."
  },
  {
    id: "lilac-jewel-saree",
    name: "Lilac Jewel Saree",
    category: "sarees",
    categoryLabel: "Sarees",
    price: 12800,
    image: "assets/products/lilac-jewel-saree.webp",
    tone: "#e6dfee",
    badge: "Soft Occasion",
    sizes: ["Free Size"],
    description: "An understated lilac drape elevated with jewel-like accents and a deep berry blouse."
  },
  {
    id: "ivory-indigo-saree",
    name: "Ivory Indigo Motif Saree",
    category: "sarees",
    categoryLabel: "Sarees",
    price: 11800,
    image: "assets/products/ivory-indigo-saree.webp",
    tone: "#e6e5e1",
    badge: "Minimal",
    sizes: ["Free Size"],
    description: "A refined ivory saree punctuated with indigo motifs and a clean contrasting blouse."
  },
  {
    id: "sage-floral-saree",
    name: "Sage Floral Saree",
    category: "sarees",
    categoryLabel: "Sarees",
    price: 15600,
    image: "assets/products/sage-floral-saree.webp",
    tone: "#e2e9df",
    badge: "New Edit",
    sizes: ["Free Size"],
    description: "A soft sage drape with romantic floral embroidery, delicate tassels and a matching statement blouse."
  },
  {
    id: "noir-jacket-saree",
    name: "Noir Embroidered Jacket Saree",
    category: "sarees",
    categoryLabel: "Sarees",
    price: 18900,
    image: "assets/products/noir-jacket-saree.webp",
    tone: "#dedde9",
    badge: "Runway Edit",
    sizes: ["Free Size"],
    description: "A dramatic black draped saree paired with a sculptural, vividly embroidered cropped jacket."
  },
  {
    id: "ivory-floral-saree",
    name: "Ivory Floral Appliqué Saree",
    category: "sarees",
    categoryLabel: "Sarees",
    price: 17400,
    image: "assets/products/ivory-floral-saree.webp",
    tone: "#e6e5e7",
    badge: "Collector's Edit",
    sizes: ["Free Size"],
    description: "An ivory and black saree transformed by oversized floral appliqué and a graphic scalloped blouse."
  },
  {
    id: "coral-grey-saree",
    name: "Coral Grey Geometric Saree",
    category: "sarees",
    categoryLabel: "Sarees",
    price: 12500,
    image: "assets/products/coral-grey-saree.webp",
    tone: "#e7dfdc",
    badge: "Modern Classic",
    sizes: ["Free Size"],
    description: "A cool grey drape edged with geometric detailing and paired with a vivid coral blouse."
  }
];
